export const LOAD_HOTELS = "LOAD_HOTELS";
export const SET_SORT1 = "SET_SORT1";
export const SET_SORT2 = "SET_SORT2";
export const PAGE_LOC = "PAGE_LOC";
export const SET_LOADING = "SET_LOADING";

export const SET_RESERVATION_DATES = "SET_RESERVATION_DATES";
export const SET_RESERVATION_APARTMENT = "SET_RESERVATION_APARTMENT";
export const SET_TRIP = "SET_TRIP";